#resources
vocab_path: '/media/data/LuoTing/local/work_space/out/step_1/Part_dataset/vocabulary.pkl'
vocab_path_14469: '/media/data/LuoTing/local/work_space/out/step_1/Part_dataset/vocabulary.pkl'

#compute ciderD ti-idf
cached_tokens: '/media/data/LuoTing/local/work_space/out/step_1/Part_dataset/artemis-idxs.p'
#compute Emo_Acc
text2emo_path: '/media/data/LuoTing/local/work_space/neural_nets/txt_to_emotion/lstm_based/best_model.pt'

#gt and gen
references_pkl_file: '/media/data/LuoTing/local/work_space/out/step_1/Part_dataset/artemis_gt_references_grouped.pkl'
captions_pkl_file: '/media/data/LuoTing/local/work_space/out_small/step_3/12-05-2022-15-34-47/result_1.pkl'

#out file
save_file: '/media/data/LuoTing/local/work_space/out_small/step_4/12-05-2022-15-34-47'