use_emo_grounding: True
use_scst_training: False

#data
log_dir: '/media/data/LuoTing/local/work_space/out_original/step_2'
data_dir: '/media/data/LuoTing/local/work_space/out/step_1/All_dataset'
img_dir: '/media/data/databases/artemis/wikiart'
file_name: 'artemis_preprocessed_enhance.csv'

#reward,cider,ciderD,spice,meteor,rouge,bleu,emo_alignment,lcs
eval_metrics: ['ciderD']
cached_tokens: '/media/data/LuoTing/local/work_space/out/step_1/All_dataset/artemis-idxs.p'

#rl params
beam_size: 5
sampling_config_file: '/media/data/LuoTing/local/work_space/artemis-master/artemis/data/speaker_sampling_configs/selected_hyper_params.json.txt'

#rl training
gt_json: '/media/data/LuoTing/local/work_space/out/step_1/All_dataset/artemis_emogt_encoded_enhance.json'
references_pkl_file: '/media/data/LuoTing/local/work_space/out/step_1/All_dataset/artemis_gt_references_grouped.pkl'
sprcial_word: '/media/data/LuoTing/local/work_space/out/step_1/All_dataset/special_words.json'

img2emo_checkpoint: '/media/data/LuoTing/local/work_space/neural_nets/img_to_emotion/best_model.pt'
text2emo_path: '/media/data/LuoTing/local/work_space/neural_nets/txt_to_emotion/lstm_based/best_model.pt'
model_ckp: '/media/data/LuoTing/local/work_space/out/step_2/10-13-2022-21-50-39/checkpoints/best_model_xe.pt'

num_classes: 9
num_maps: 4
feature_extract: False
emotion_histogram: /media/data/LuoTing/local/work_space/artemis-master/artemis/data/image-emotion-histogram.csv
mode: original_model

num_workers: 20