#resources
img_dir : 'F:/dataset/Image/ArtEmis/wikiart'
out_file : 'F:/work/Image_emotion_analysis/artemis-master/artemis_out/step3/RAIVS_12-21-2022-02-22-21'
img2emo_checkpoint : 'F:/work/Image_emotion_analysis/artemis-master/artemis_out/model/img_to_emotion/best_model.pt'
# 


# 'original','img2emo_checkpoint','wscnet'


# 

#train settings
speaker_saved_args: 'F:/work/Image_emotion_analysis/artemis-master/artemis_out/step2/12-21-2022-02-22-21/config.json.txt'
# '/media/data/LuoTing/local/work_space/out/step_2/11-28-2022-19-39-51/config.json.txt'
#trained model
speaker_checkpoint : 'F:/work/Image_emotion_analysis/artemis-master/artemis_out/step2/12-21-2022-02-22-21/checkpoints/best_model.pt'
#'/media/data/LuoTing/local/work_space/out/step_2/11-28-2022-19-39-51/checkpoints/best_model_xe.pt'
sampling_config_file : 'F:/work/Image_emotion_analysis/artemis-master/artemis/data/speaker_sampling_configs/selected_hyper_params.json.txt'

num_classes: 9
num_maps: 4
feature_extract: False
emotion_histogram: 'F:/work/Image_emotion_analysis/artemis-master/artemis/data/image-emotion-histogram.csv'
mode: 'original_model'