#resources
vocab_path: 'F:/work/Image_emotion_analysis/artemis-master/small_out/step1/vocabulary.pkl'
vocab_path_14469: 'F:/work/Image_emotion_analysis/artemis-master/artemis_out/step1/vocabulary.pkl'

#compute ciderD ti-idf
cached_tokens: 'F:/work/Image_emotion_analysis/artemis-master/small_out/step1/artemis-idxs.p'
#compute Emo_Acc
text2emo_path: 'F:/work/Image_emotion_analysis/artemis-master/artemis_out/model/txt_to_emotion/lstm_based/best_model.pt'

#gt and gen
references_pkl_file: 'F:/work/Image_emotion_analysis/artemis-master/small_out/step1/artemis_gt_references_grouped.pkl'
captions_pkl_file: 'F:/work/Image_emotion_analysis/artemis-master/small_out/step3/02-21-2023-21-50-28/result_1.pkl'

#out file
save_file: 'F:/work/Image_emotion_analysis/artemis-master/small_out/step4/XE_02-21-2023-21-50-28'
